module.exports = {
  mode: 'jit',
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    backgroundColor: theme => ({
      ...theme('colors'),
      // macOS Background Colors
      'mac-dark': '#1C1C1E',
      'mac-darker': '#000000',
      'mac-gray': '#2C2C2E',
      'mac-light-gray': '#3A3A3C',
      'mac-lighter-gray': '#48484A',
      'mac-window': '#ECECEC',
      'mac-window-dark': '#2D2D30',
      'mac-sidebar': '#F5F5F7',
      'mac-sidebar-dark': '#1E1E1E',
      'mac-blue': '#007AFF',
      'mac-blue-hover': '#0056CC',
      'mac-red': '#FF3B30',
      'mac-yellow': '#FFCC00',
      'mac-green': '#34C759',
      'mac-dock': 'rgba(255, 255, 255, 0.15)',
      'mac-dock-dark': 'rgba(0, 0, 0, 0.3)',
      'mac-translucent': 'rgba(255, 255, 255, 0.8)',
      'mac-translucent-dark': 'rgba(0, 0, 0, 0.6)',
      
      // Legacy Ubuntu colors (for gradual migration)
      'ub-grey': '#1C1C1E',
      'ub-warm-grey': "#48484A",
      'ub-cool-grey': "#2C2C2E",
      'ub-orange': "#007AFF",
      'ub-lite-abrgn': "#007AFF",
      'ub-med-abrgn': "#0056CC",
      'ub-drk-abrgn': "#1C1C1E",
      'ub-window-title': "#2D2D30",
      'ub-gedit-dark': "#1C1C1E",
      'ub-gedit-light': "#2C2C2E",
      'ub-gedit-darker': "#000000",
    }),
    textColor: theme => ({
      ...theme('colors'),
      // macOS Text Colors
      'mac-primary': '#FFFFFF',
      'mac-secondary': '#EBEBF5',
      'mac-tertiary': '#EBEBF599',
      'mac-quaternary': '#EBEBF54D',
      'mac-primary-dark': '#000000',
      'mac-secondary-dark': '#3C3C43',
      'mac-tertiary-dark': '#3C3C4399',
      'mac-blue': '#007AFF',
      'mac-red': '#FF3B30',
      'mac-green': '#34C759',
      'mac-yellow': '#FFCC00',
      
      // Legacy Ubuntu colors (for gradual migration)
      'ubt-grey': '#FFFFFF',
      'ubt-warm-grey': "#EBEBF5",
      'ubt-cool-grey': "#3C3C43",
      'ubt-blue': "#007AFF",
      'ubt-green': "#34C759",
      'ubt-gedit-orange': "#FFCC00",
      'ubt-gedit-blue': "#007AFF",
      'ubt-gedit-dark': "#007AFF",
    }),
    borderColor: theme => ({
      ...theme('colors'),
      DEFAULT: theme('colors.gray.300', 'currentColor'),
      'mac-border': '#3C3C43',
      'mac-border-light': '#D1D1D6',
      'mac-blue': '#007AFF',
      'ubb-orange': '#007AFF'
    }),
    minWidth: {
      '0': '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      'full': '100%',
    },
    minHeight: {
      '0': '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      'full': '100%',
    },
    extend: {
      zIndex: {
        '-10': '-10',
      },
      fontFamily: {
        'mac': ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'SF Pro Text', 'system-ui', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'mac-mono': ['SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', 'monospace'],
      },
      borderRadius: {
        'mac-sm': '6px',
        'mac': '8px',
        'mac-lg': '12px',
        'mac-xl': '16px',
        'mac-2xl': '20px',
        'mac-window': '12px',
        'mac-button': '6px',
      },
      boxShadow: {
        'mac-sm': '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
        'mac': '0 4px 6px rgba(0, 0, 0, 0.07), 0 1px 3px rgba(0, 0, 0, 0.06)',
        'mac-md': '0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)',
        'mac-lg': '0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)',
        'mac-xl': '0 25px 50px rgba(0, 0, 0, 0.25)',
        'mac-window': '0 8px 32px rgba(0, 0, 0, 0.3), 0 0 0 1px rgba(255, 255, 255, 0.05)',
        'mac-dock': '0 0 0 1px rgba(255, 255, 255, 0.1), 0 10px 30px rgba(0, 0, 0, 0.3)',
        'mac-inner': 'inset 0 1px 0 rgba(255, 255, 255, 0.1)',
      },
      backdropBlur: {
        'mac': '20px',
        'mac-lg': '40px',
      },
      animation: {
        'mac-bounce': 'macBounce 0.6s ease-in-out',
        'mac-scale': 'macScale 0.2s ease-out',
      },
      keyframes: {
        macBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        macScale: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}