# .github/workflows/update-projects.yml
name: Update Projects List

on:
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2AM
  workflow_dispatch:

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install fetch
        run: npm install node-fetch

      - name: Run fetch script
        run: node scripts/fetch-projects.js

      - name: Commit updated projects.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/projects.json
          git commit -m "chore: auto-update projects.json [bot]" || echo "No changes"
          git push
